from inference.pretrained import Pretrained
from prompt.supported import SupportedToken
from graph.graph import Graph
from lm.generate import generate
from lm.critique_supported import critique_supported

graph = Graph()
inference = Pretrained("HlaH/Llama3-ChatQA-Critic-PubMedQA")
graph.set_memory("critique_supported_inference", inference)
graph.add_node("critique", critique_supported)

graph.run("critique",
          {
              "query": "what is cancer",
              "documents": [
                  "htmlSkip to main contentEmailWhat Is Cancer?Get email updates from NCI on cancer health information, news, and other topicsGet email updates from NCIThe Definition of CancerCancer is a disease in which some of the body’s cells grow uncontrollably and spread to other parts of the body.Cancer can start almost anywhere in the human body, which is made up of trillions of cells. Normally, human cells grow and multiply (through a process calledcelldivision) to form new cells as the body needs them. When cells grow old or become damaged, they die, and new cells take their place.Sometimes this orderly process breaks down, and abnormal or damaged cells grow and multiply when they shouldn’t. These cells may form tumors, which are lumps of tissue. Tumors can be cancerous or not cancerous (benign).",
                  "htmlSkip to main contentWhat is cancer?Cancer starts when cells change abnormallyThere are more than 200 different types of cancer.1 in 2xa0people in the UK will get cancer in their lifetime.Thanks to research many people are cured.How does cancer start?Cancer grows as cells multiply over and overCancer starts when gene changes make one cell or a few cells begin to grow and multiply too much. This may cause a growth called a tumour.How does cancer grow?",
                  "But in some people cancer can return.Some cancers can’t be cured but treatment is often able to control them for some years.Why do some cancers come back?There are 5 main cancer groupsCancers are divided into groups according to the type of cell they start from. They includeWhat are the different cancer groups?Stages and grading of cancerStaging and grading give an idea of how quickly a cancer may grow and which treatments may work bestThe stage of a cancer means how big it is and whether it has spread.Grading looks at how abnormalthe cancer cells are.What are the stages of cancer?What is cancer grading?Cancer Research UK's informationis generously sponsored byDangoor Educationto honour the lives ofSir Naim Dangoor CBEand Mrs Renée Dangoor.Rate this page:",
                  "interestingly , identical cytokines and identical cells quite commonly have different and often opposite effects on tumor cells ' behavior , depending again on the context . \n , , ,   the behavior of cancer cells is influenced by various other cells and molecules . \n , extracellular matrix also regulates normal development and function of an organism : embryogenesis , growth and differentiation of cells , gene function , apoptosis , tissue specificity , tissue structure , and normal homeostasis of the adult organism . \n the classic feature of cancer tissue is the disturbed communication between cells and extracellular matrix . \n , , breaking cell - cell bonds and intercellular communication is known to induce neoplastic behavior .",
                  "For example, breast cancer thatxa0forms a metastatic tumor in the lung is metastatic breast cancer, not lung cancer.Under a microscope, metastatic cancer cells generally look the same as cells of the original cancer. Moreover, metastatic cancer cells and cells of the original cancer usually have some molecular features in common, such as the presence of specificchromosomechanges.In some cases, treatment may help prolong the lives of people with metastatic cancer. In other cases, the primary goal of treatmentxa0for metastatic cancer is to control the growth of the cancer or to relieve symptoms it is causing.",
                  "Most cancer-causing DNA changes occur in sections of DNA called genes. These changes are also called genetic changes.A DNA change can cause genes involved in normal cell growth to become oncogenes. Unlike normal genes, oncogenes cannot be turned off, so they cause uncontrolled cell growth.In normal cells, tumor suppressor genes prevent cancer by slowing or stopping cell growth. DNA changes that inactivate tumor suppressor genes can lead to uncontrolled cell growth and cancer.Within a tumor, cancer cells are surrounded by a variety of immune cells, fibroblasts, molecules, and blood vessels—what’s known as the tumor microenvironment. Cancer cells can change the microenvironment, which in turn can affect how cancer grows and spreads.Immune system cells can detect and attack cancer cells.",
                  "Some cancers of the bladder, ureters, and kidneys are transitional cell carcinomas.SarcomaSarcomas are cancers that form in bone and soft tissues, including muscle, fat, blood vessels,lymph vessels, and fibrous tissue (such as tendons and ligaments).Osteosarcoma is the most common cancer of bone. The most common types of soft tissue sarcoma areleiomyosarcoma,Kaposi sarcoma,malignant fibrous histiocytoma,liposarcoma, anddermatofibrosarcoma protuberans.Our page onsoft tissue sarcomahas more information.LeukemiaCancers that begin in the blood-forming tissue of thebone marroware called leukemias. These cancers do not form solid tumors.",
                  "we aimed to use this meeting series to bring together researchers who have been studying cancer from very different perspectives to develop novel views , ask deeper questions about the essence of cancer , and generate new dialogs / collaborations leading to fundamentally new understanding about cancer at the systems level .",
                  "According to the 2022 Annual Report on Cancer, the disease:Almost anyone may develop cancer, but it typically affects people aged 60 and older.AdvertisementCleveland Clinic is a non-profit academic medical center. Advertising on our site helps support our mission. We do not endorse non-Cleveland Clinic products or services.PolicySymptoms and CausesWhat are cancer symptoms?Cancer is a complicated disease. You can have cancer for years without developing symptoms. Other times, cancer may cause noticeable symptoms that get worse very quickly. Many cancer symptoms resemble other, less serious illnesses. Having certain symptoms doesn’t mean you have cancer.",
                  "Cancerous tumors spread into, or invade, nearby tissues and can travel to distant places in the body to form new tumors (a process calledmetastasis). Cancerous tumors may also be calledmalignanttumors. Many cancers form solid tumors, but cancers of the blood, such asleukemias, generally do not.Benign tumors do not spread into, or invade, nearby tissues. When removed, benign tumors usually don’t grow back, whereas cancerous tumors sometimes do. Benign tumors can sometimes be quite large, however. Some can cause serious symptoms or be life threatening, such as benign tumors in the brain.Differences between Cancer Cells and Normal CellsGet Answers >​​"
              ],
              "result": "Cancer is a disease in which some of the body’s cells grow uncontrollably and spread to other parts of the body."
          })
